language: cpp
compiler:
  - gcc
  - clang
jdk:
  - oraclejdk7
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - yes | sudo add-apt-repository ppa:beineri/opt-qt52
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq zlib1g-dev qt52base qt52declarative
script: source /opt/qt52/bin/qt52-env.sh && qmake testUnit.pro && make && ./testUnitJvmLauncher
after_success:
  - export QT_LIBRARY_PATH=/opt/qt52/lib
  - export JAVA_HOME=/usr/lib/jvm/java-7-oracle
  - export JRE_HOME=/usr/lib/jvm/java-7-oracle/jre
  - source /opt/qt52/bin/qt52-env.sh && qmake JvmLauncher.pro && make install
