language: cpp
compiler:
  - gcc
  - clang
jdk:
  - oraclejdk7
env:
  global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=jvm_launcher_repo"
    - secure: "bUWVI/qd2FujM1ZVMKq6uTRVpSZWI4TZG3uM7tSKQ5h3+rryUPfn2A/RpsFHqTtNsflGc9iIdTJqP2KS8UOjZB/c5aD+HOtSga70k6t0I7FWsss0caO/5r592x58I6wB4plOcNQQouE2RrJCKxdnKR6Z8CrXokO8UtpBMN5xTBM="
    - secure: "W/FpbxLRoAONuET53bJgg1vh7GUh15ytyRUQuUuOsJPUjMVd6OugFy6JFmXCBLYwPVANILCsjhi4SnTFS0od+1n6NDlROEcF+L3vVetmoU02mNHTnVPHpqrv/sEcDJ3ltETG/gqphQaYhSlB9rFCs3b0WodvyNwURxWgN5R5npU="
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - yes | sudo add-apt-repository ppa:beineri/opt-qt52
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq --force-yes zlib1g-dev qt52base qt52declarative
  - gem install travis-artifacts
before script:
  - export QT_LIBRARY_PATH=/opt/qt52/lib
  - export JAVA_HOME=/usr/lib/jvm/java-7-oracle
  - export JRE_HOME=/usr/lib/jvm/java-7-oracle/jre
script: 
  - source /opt/qt52/bin/qt52-env.sh && qmake testUnit.pro && make && ./testUnitJvmLauncher
  - make clean
  - rm Makefile
  - source /opt/qt52/bin/qt52-env.sh && qmake JvmLauncher.pro && make install
after_script:
  - travis-artifacts upload --path logs --path a/long/nested/path:short_alias
after_failure: # this will of course run only on failure
  - travis-artifacts upload --path debug/debug.log
after_success: # and this only on success
  - travis-artifacts upload --path linuxRelease.tar.gz
